
language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN=k48Y5TlZmB6CMKo5dsk2SpW8
  
install:
  - npm install

script:
  - npm run build
  - npm run test

before_install:
  - "npm config set spin false"
  - npm i -g now
  
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true